#!/usr/bin/env zsh
ANTIBODY_BINARY="/usr/bin/antibody"
antibody() {
	case "$1" in
	bundle)
		source <( $ANTIBODY_BINARY $@ ) 2> /dev/null || $ANTIBODY_BINARY $@
		;;
	*)
		$ANTIBODY_BINARY $@
		;;
	esac
}

_antibody() {
	IFS=' ' read -A reply <<< "$(echo "bundle update list home init help")"
}
compctl -K _antibody antibody

# The above configuration has been generated by `antibody init`

# install plugins via antibody
antibody bundle < ~/.zsh/plugins.txt

# enable some features from oh-my-zsh
source ~/.zsh/oh-my-zsh.zsh

# enable bash-compatible completion
autoload -U +X bashcompinit && bashcompinit

# pure prompt
fpath+=~/.zsh/functions
autoload -U promptinit && promptinit
prompt pure

source ~/.zsh/bindings.zsh
source ~/.zsh/options.zsh
source ~/.zsh/aliases.zsh

stty -ixon -ixoff

# load completion for Haskell Stack
if which stack &>/dev/null; then
    eval "$(stack --bash-completion-script stack)"
fi

# enable fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# set TERM variable on Guake terminal
# if [[ -n "${GUAKE_TAB_UUID}" ]]; then
#   export TERM=xterm-256color
# fi

# load machine-specific zsh configuration if any
# [[ -f ~/.zshrc-local ]] && source ~/.zshrc-local
