- name: Count the number of lines that are exactly 'export PATH'
  shell: "grep '^export PATH$' {{ zshenv_file }} | wc -l "
  register: path_export_count

- when: path_export_count != 0
  block:
    - name: Strip the 'export PATH' lines
      lineinfile:
        state: absent
        line: export PATH
        path: '{{ zshenv_file }}'
    - name: Add a final 'export PATH' line
      lineinfile:
        state: present
        line: "# Export PATH\nexport PATH"
        insertafter: EOF
        path: '{{ zshenv_file }}'
