---
- include: packer.yml

- hosts: all
  vars_files:
    - [ "vars/{{ ansible_hostname }}.yml", "vars/host_default.yml" ]
  become: yes
  become_user: "{{ user_name }}"
  roles:
    - { role: pacman-multilib }
    - { role: pacman-color }
    - { role: spacemacs, tags: [ 'writing', 'development', 'org' ] }
    - { role: dropbox, tags: [ 'dropbox' ] }
    - { role: dropbox-gocryptfs, tags: [ 'org', 'private' ] }
    - { role: hub, tags: [ 'development' ] }
    - { role: termite, tags: [ 'development', 'admin' ] }
    - { role: aspell, tags: [ 'writing' ] }
    - { role: xmodmap, tags: [ 'desktop' ] }
    - { role: myrepos }
    - { role: org-protocol, tags: [ 'org' ] }
    - { role: nvim, tags: [ 'vim', 'deprecated' ] }
    - { role: fcitx-japanese, tags: [ 'lang:ja', 'fcitx' ] }
    - { role: fcitx-chinese-cn, tags: [ 'lang:zh-cn', 'fcitx' ] }
    - { role: fcitx-chinese-tw, tags: [ 'lang:zh-tw', 'fcitx' ] }
    - { role: japanese-fonts, tags: [ 'lang:ja' ] }
    - { role: chinese-fonts, tags: [ 'lang:zh-cn', 'lang:zh-tw' ] }
    - { role: javascript, tags: [ 'javascript' ] }
    - { role: zsh, tags: [ 'admin', 'zsh' ] }
    - { role: fzf, tags: [ 'zsh' ] }
    - { role: pulseaudio, when: ansible_hostname == 'empower' }
    # - { role: nodm, tags: [ 'nodm', 'desktop' ] }
    - { role: pacman-haskell-core, tags: [ 'haskell' ] }
    - { role: pacman-repo, tags: [ 'archlinuxfr' ], name: archlinuxfr,
        props: "SigLevel = Never\nServer = http://repo.archlinux.fr/$arch" }
    - { role: pacman-repo, tags: [ 'archlinuxcn' ], name: archlinuxcn,
        props: "SigLevel = Optional TrustedOnly\nServer = https://cdn.repo.archlinuxcn.org/$arch" }
