---
- include: packer.yml

- hosts: all
  become: yes
  become_user: "{{ user_name }}"
  roles:
    - { role: spacemacs, tags: [ 'writing', 'development', 'org' ] }
    - { role: dropbox, tags: [ 'dropbox' ] }
    - { role: dropbox-gocryptfs, tags: [ 'org', 'private' ] }
    - { role: hub, tags: [ 'development' ] }
    - { role: termite, tags: [ 'development', 'admin' ] }
    - { role: aspell, tags: [ 'writing' ] }
    - { role: xmodmap, tags: [ 'desktop' ] }
    - { role: myrepos }
