---
# Install packer for AUR support if the operating system is Arch Linux
- hosts: all
  tasks:
    - name: Check OS distribution
      setup:
        filter: ansible_os_family
      register: distribution
    - when: distribution == "Arch Linux"
      import_tasks: packer.yml

- hosts: all
  vars_files:
    - [ "vars/{{ ansible_hostname }}.yml", "vars/host_default.yml" ]
  become: yes
  become_user: "{{ user_name }}"
  roles:
    - { role: archlinux, when: ansible_os_family == "Arch Linux" }
    - { role: spacemacs, tags: [ 'writing', 'development', 'org' ] }
    - { role: dropbox, tags: [ 'dropbox' ] }
    - { role: dropbox-gocryptfs, tags: [ 'org', 'private' ] }
    - { role: hub, tags: [ 'development' ] }
    - { role: termite, tags: [ 'development', 'admin' ] }
    - { role: aspell, tags: [ 'writing' ] }
    - { role: xmodmap, tags: [ 'desktop' ] }
    - { role: org-protocol, tags: [ 'org' ] }
    - { role: nvim, tags: [ 'vim', 'deprecated' ] }
    - { role: fcitx-japanese, tags: [ 'lang:ja', 'fcitx' ] }
    - { role: fcitx-chinese-cn, tags: [ 'lang:zh-cn', 'fcitx' ] }
    - { role: fcitx-chinese-tw, tags: [ 'lang:zh-tw', 'fcitx' ] }
    - { role: japanese-fonts, tags: [ 'lang:ja' ] }
    - { role: chinese-fonts, tags: [ 'lang:zh-cn', 'lang:zh-tw' ] }
    - { role: javascript, tags: [ 'javascript' ] }
    - { role: zsh, tags: [ 'admin', 'zsh' ] }
    - { role: zshenv-add, template: 'apikeys' }
    - { role: zshenv-add, template: 'chromium' }
    - { role: fzf, tags: [ 'zsh' ] }
    - { role: haskell-stack, tags: [ 'haskell' ] }
    # - { role: pulseaudio, when: ansible_hostname == 'empower' }
    # - { role: nodm, tags: [ 'nodm', 'desktop' ] }
    - { role: user-scripts }
    - { role: github-personal, tags: [ 'github', 'symlink', 'akirak' ] }
    # Run this in the very end of this playbook
    - { role: zshenv-finalize, tags: [ 'zsh' ] }
