---
- hosts: all

  vars_files:
    # Load names of packages depending on the distribution
    - [ "vars/apps_{{ ansible_os_family }}.yml", "vars/apps_default.yml" ]

  vars:
    zshenv_file: "{{ '~/.zshenv' | expanduser }}"
    # To install dotfiles, you must give playbook_dir as an extra variable
    dotfiles_dir: "{{ playbook_dir }}/files/dotfiles"

  pre_tasks:

    - name: check if this playbook is run as a user
      include_tasks: tasks/check-user.yml

    - include_role:
        name: profile
        tasks_from: initialize.yml

  roles:

    # - name: dropbox
    #   tags: [ 'dropbox' ]

    # - name: keybase
    #   tags: [ 'keybase' ]

    # TODO: integrate dotfiles, user-scripts, link-dotfiles, mackup
    - name: dotfiles
      tags: [ 'dotfiles' ]
  #   - { role: user-scripts }

    # emacs, EDITOR, and org-protocol
    - name: emacs
      tags: [ 'emacs' ]

    # web browser
    - name: web
      tags: [ 'web', 'x11' ]

    # zsh executable as well as config
    - name: zsh
      tags: [ 'zsh', 'dotfiles' ]

    # # fonts and input method (only Chinese and Japanese for now)
    # - name: cjk
    #   tags: [ 'x11', 'cjk' ]

  #   - { role: fcitx-japanese, tags: [ 'lang:ja', 'fcitx' ] }
  #   - { role: fcitx-chinese-cn, tags: [ 'lang:zh-cn', 'fcitx' ] }
  #   - { role: fcitx-chinese-tw, tags: [ 'lang:zh-tw', 'fcitx' ] }
  #   - { role: japanese-fonts, tags: [ 'lang:ja' ] }
  #   - { role: chinese-fonts, tags: [ 'lang:zh-cn', 'lang:zh-tw' ] }

    # generate ~/.Xmodmap depending on the host name
    - name: xmodmap
      tags: [ 'x11', 'dotfiles' ]

    # - name: javascript
    #   tags: [ 'javascript', 'programming' ]

    # - name: haskell-stack
    #   tags: [ 'haskell', 'programming' ]

    # questionable
    #   - { role: spacemacs, tags: [ 'writing', 'development', 'org' ] }
    #   - { role: termite, tags: [ 'development', 'admin' ] }
    #   - { role: aspell, tags: [ 'writing' ] }

  post_tasks:

    - include_role:
        name: profile
        tasks_from: finalize.yml
