---
- name: check if packer is installed
  stat:
    path: /usr/bin/packer
  register: packer

- when: not packer.stat.exists
  block:

    - name: "install prerequisites for installing pacman"
      pacman:
        name: "{{ package }}"
        state: present
      with_items:
        - sudo
      loop_control:
        loop_var: package

    - when: ansible_user_id == 'root'
      include_tasks: packer-as-root.yml

    - when: ansible_user_id != 'root'
      include_tasks: packer-as-user.yml
