---
- name: install dotfiles using mackup
  include_tasks: mackup.yml

- name: add scripts to PATH
  include_role: name=profile
  vars:
    dest: .zshenv
    name: scripts
    content: |
      # Add my user scripts to PATH
      PATH="{{ playbook_dir }}/bin:$PATH"
      export PATH
