---
- name: install miscellaneous packages
  package:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - aspell
    - aspell-en

- name: install miscellaneous packages (graphical)
  package:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - tk
  tags: x11
