---
- name: set EDITOR to emacsclient
  include_role: name=profile
  vars:
    dest: .zshenv
    name: editor
    content: |
      # Set the default editor to emacsclient
      export EDITOR="emacsclient --alternate-editor=emacs"

- name: create a directory for desktop files
  file:
    path: "{{ '~/.local/share/applications' | expanduser }}"
    state: directory

- name: install a desktop file for emacsclient
  copy:
    src: emacsclient.desktop
    dest: "{{ '~/.local/share/applications/emacsclient.desktop' | expanduser }}"
