---
- name: install emacs
  become: yes
  package:
    name: emacs
    state: present
  tags: package

- include_tasks: emacsclient.yml
  tags: emacsclient

- include_tasks: org-protocol.yml
  tags: org-protocol
