---
- name: ensure mimeapps.list contains an entry for org-protocol
  ini_file:
    dest: "{{ '~/.local/share/applications/mimeapps.list' | expanduser }}"
    section: "Default Applications"
    option: x-scheme-handler/org-protocol
    value: emacsclient.desktop
    backup: yes
  notify: update-desktop-database
