---
- hosts: all

  vars:
    # Machines that have Ansible are likely to have Python 2 as well
    ansible_python_interpreter: /usr/bin/python2

  pre_tasks:

    # Install and configure pacman-related stuffs if and only if the target is Arch Linux
    - when: ansible_os_family == 'Archlinux'
      block:
        - name: install packer AUR helper
          include_tasks: tasks/aur-packer.yml
          tags: [ 'aur' ]

        - name: add pacman repositories
          include_tasks: tasks/arch-pacman-repos.yml

        - name: run other pre-tasks for Arch Linux
          include_tasks: tasks/arch-config.yml

        - name: update the pacman databases
          pacman: update_cache=yes

    - name: get user_name variable
      include_tasks: tasks/set-user_name.yml

    - name: create a user and a group for you
      when: whoami.stdout == 'root'
      include_tasks: tasks/create-user.yml
      vars:
        group_name: "{{ user_name }}"

  roles:

    # Install X server, a display manager, a window manager, etc.
    # Installed applications may differ (or even may not be installed)
    # depending on the distribution.
    - name: x11
      tags: ['x11']
