---
- name: install basic packages and utilities for the X Window System
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - xorg-server
    - xorg-xinit
    - xorg-xmodmap
    - xorg-xprop
    - xorg-xset
    - xorg-setxkbmap

- name: set a video driver
  include_vars: "{{ item }}"
  with_first_found:
    - "video-{{ ansible_hostname }}.yml"
    - "video-vesa.yml"

- name: install the video driver
  pacman:
    name: "{{ arch_video_driver_package }}"

# TODO: install a display manager
# - name: install a display manager (LightDM)
#   include_role:
#     name: lightdm
#     tasks_from: archlinux
