# roles/zsh/meta/main.yml for Ansible
---
dependencies:
  - dotfiles
  - { role: link-dotfile, path: .zsh }
  - { role: package, pacman: zsh }
  - { role: package, use_archlinux_aur: yes, aur: antibody }
