---
- name: check if packer is installed
  stat:
    path: /usr/bin/packer
  register: packer

- when: not packer.stat.exists
  become: yes
  block:

    - name: "install required packages using pacman"
      pacman:
        name: "{{ package }}"
        state: present
      with_items:
        - shadow
        - sudo
        - grep
      loop_control:
        loop_var: package

    - name: "create aur user"
      user:
        name: aur
        state: present
        createhome: no

    - name: "add aur user to sudoers"
      lineinfile:
        line: "aur ALL=(ALL) NOPASSWD: ALL"
        path: /etc/sudoers

    - name: "install packer AUR helper"
      script: utils/install_packer.sh
      become_user: aur

    - name: "delete aur user from sudoers"
      lineinfile:
        line: "aur ALL=(ALL) NOPASSWD: ALL"
        path: /etc/sudoers
        state: absent

    - name: "remove aur user"
      user:
        name: aur
        state: absent
