---

- when: >
    ansible_os_family == "Arch Linux" and
    not (use_archlinux_aur is defined and use_archlinux_aur)
  name: "install {{ pacman }} from pacman"
  become_user: root
  pacman:
    name: "{{ pacman }}"
    state: present

- when: >
    ansible_os_family == "Arch Linux"
    and use_archlinux_aur is defined and use_archlinux_aur
  name: "install {{ aur }} from AUR"
  become_user: root
  packer:
    name: "{{ aur }}"
    state: present

- when: ansible_os_family == "Solus"
  name: "install {{ eopkg }} using eopkg"
  block:
    - when: eopkg is not defined
      fail:
        msg: "parameter eopkg is not defined"

    - become_user: root
      shell: "eopkg install -y {{ eopkg }}"
