---

- when: >
    ansible_os_family == "Arch Linux" and
    not (use_archlinux_aur is defined and use_archlinux_aur)
  name: "install {{ pacman }} from pacman"
  become_user: root
  pacman:
    name: "{{ pacman }}"
    state: present

- when: >
    ansible_os_family == "Arch Linux"
    and use_archlinux_aur is defined and use_archlinux_aur
  name: "install {{ aur }} from AUR"
  become_user: root
  packer:
    name: "{{ aur }}"
    state: present
